### PR TITLE
component bugfix

### PR DESCRIPTION
**Pull request by songzhiwen**
fix the bug of the component AlertExample.vue and VADirectChat.vue

### CODE REVIEW

**Comment by devjin0617** [comment]
thanks!

**Comment by songzhiwen** [comment]
I forget a problem that the Column.vue's property class reports the class name is a key word when I custom a value and delivery it to Column.vue component. You may have a test for it! Thanks for your project

**Comment by WinnerSong** [comment]
When do you public the latest version to the npm repository?Each of my team has many warning messages when they compile the code

**Comment by devjin0617** [comment]
@WinnerSong Thanks! Will be updated in a few days

**Comment by devjin0617** [comment]
@WinnerSong updated! https://www.npmjs.com/package/vue2-admin-lte

**Pull request merged**
